X2019.SOI.RENAME <- function(d, ein='ein'){ 

  nm <- names(d)
  nm[ nm == ein ] <- 'F9_00_ORG_EIN' 
  names(d) <- nm 
  d <- dplyr::rename( d, 
    F9_10_ASSET_CASH_SAVING_EOY = nonintcashend, 
    F9_08_REV_PROG_TOT_TOT = totprgmrevnue, 
    F9_10_LIAB_TOT_EOY = totliabend, 
    F9_10_ASSET_ACC_NET_EOY = accntsrcvblend, 
    F9_09_EXP_DEPREC_TOT = deprcatndepletn, 
    F9_10_ASSET_SAVING_EOY = svngstempinvend, 
    F9_10_ASSET_TOT_EOY = totassetsend, 
    F9_01_EXP_TOT_CY = totfuncexpns, 
    F9_10_NAFB_UNRESTRICT_EOY = unrstrctnetasstsend, 
    F9_01_REV_TOT_CY = totrevenue, 
    F9_10_ASSET_PLEDGE_NET_EOY = pldgegrntrcvblend, 
    F9_10_NAFB_TOT_EOY = totnetassetend, 
    F9_10_ASSET_INV_SALE_EOY = invntriesalesend, 
    F9_10_ASSET_EXP_PREPAID_EOY = prepaidexpnsend, 
    F9_10_LIAB_ACC_PAYABLE_EOY = accntspayableend, 
    F9_10_LIAB_GRANT_PAYABLE_EOY = grntspayableend, 
    F9_08_REV_CONTR_TOT = totcntrbgfts, 
    F9_08_REV_OTH_FUNDR_NET_TOT = netincfndrsng, 
    F9_08_REV_OTH_ROY_TOT = royaltsinc, 
    F9_08_REV_OTH_INV_NET_TOT = netincsales, 
    F9_08_REV_MISC_TOT_TOT = miscrevtot11e, 
    F9_08_REV_OTH_INVEST_INCOME_TOT = invstmntinc, 
    F9_08_REV_OTH_INVEST_BOND_TOT = txexmptbndsproceeds , 
    F9_08_REV_OTH_RENT_NET_TOT = netrntlinc , 
    F9_08_REV_OTH_SALE_GAIN_NET_TOT = netgnls ) %>%  
  dplyr::select( F9_00_ORG_EIN, F9_10_ASSET_CASH_SAVING_EOY, F9_08_REV_PROG_TOT_TOT, F9_10_LIAB_TOT_EOY, F9_10_ASSET_ACC_NET_EOY, F9_09_EXP_DEPREC_TOT, F9_10_ASSET_SAVING_EOY, F9_10_ASSET_TOT_EOY, F9_01_EXP_TOT_CY, F9_10_NAFB_UNRESTRICT_EOY, F9_01_REV_TOT_CY, F9_10_ASSET_PLEDGE_NET_EOY, F9_10_NAFB_TOT_EOY, F9_10_ASSET_INV_SALE_EOY, F9_10_ASSET_EXP_PREPAID_EOY, F9_10_LIAB_ACC_PAYABLE_EOY, F9_10_LIAB_GRANT_PAYABLE_EOY, F9_08_REV_CONTR_TOT, F9_08_REV_OTH_FUNDR_NET_TOT, F9_08_REV_OTH_ROY_TOT, F9_08_REV_OTH_INV_NET_TOT, F9_08_REV_MISC_TOT_TOT, F9_08_REV_OTH_INVEST_INCOME_TOT, F9_08_REV_OTH_INVEST_BOND_TOT, F9_08_REV_OTH_RENT_NET_TOT, F9_08_REV_OTH_SALE_GAIN_NET_TOT )

}


X2016.SOI.RENAME <- function(d, ein='ein'){ 

  nm <- names(d)
  nm[ nm == ein ] <- 'F9_00_ORG_EIN' 
  names(d) <- nm 
  d <- dplyr::rename( d, 
    F9_10_ASSET_CASH_SAVING_EOY = nonintcashend, 
    F9_08_REV_PROG_TOT_TOT = totprgmrevnue, 
    F9_10_LIAB_TOT_EOY = totliabend, 
    F9_10_ASSET_ACC_NET_EOY = accntsrcvblend, 
    F9_09_EXP_DEPREC_TOT = deprcatndepletn, 
    F9_10_ASSET_SAVING_EOY = svngstempinvend, 
    F9_10_ASSET_TOT_EOY = totassetsend, 
    F9_01_EXP_TOT_CY = totfuncexpns, 
    F9_10_NAFB_UNRESTRICT_EOY = unrstrctnetasstsend, 
    F9_01_REV_TOT_CY = totrevenue, 
    F9_10_ASSET_PLEDGE_NET_EOY = pldgegrntrcvblend, 
    F9_10_NAFB_TOT_EOY = totnetassetend, 
    F9_10_ASSET_INV_SALE_EOY = invntriesalesend, 
    F9_10_ASSET_EXP_PREPAID_EOY = prepaidexpnsend, 
    F9_10_LIAB_ACC_PAYABLE_EOY = accntspayableend, 
    F9_10_LIAB_GRANT_PAYABLE_EOY = grntspayableend, 
    F9_08_REV_CONTR_TOT = totcntrbgfts, 
    F9_08_REV_OTH_FUNDR_NET_TOT = netincfndrsng, 
    F9_08_REV_OTH_ROY_TOT = royaltsinc, 
    F9_08_REV_OTH_INV_NET_TOT = netincsales, 
    F9_08_REV_MISC_TOT_TOT = miscrevtot11e, 
    F9_08_REV_OTH_INVEST_INCOME_TOT = invstmntinc, 
    F9_08_REV_OTH_INVEST_BOND_TOT = txexmptbndsproceeds , 
    F9_08_REV_OTH_RENT_NET_TOT = netrntlinc , 
    F9_08_REV_OTH_SALE_GAIN_NET_TOT = netgnls ) %>%  
  dplyr::select( F9_00_ORG_EIN, F9_10_ASSET_CASH_SAVING_EOY, F9_08_REV_PROG_TOT_TOT, F9_10_LIAB_TOT_EOY, F9_10_ASSET_ACC_NET_EOY, F9_09_EXP_DEPREC_TOT, F9_10_ASSET_SAVING_EOY, F9_10_ASSET_TOT_EOY, F9_01_EXP_TOT_CY, F9_10_NAFB_UNRESTRICT_EOY, F9_01_REV_TOT_CY, F9_10_ASSET_PLEDGE_NET_EOY, F9_10_NAFB_TOT_EOY, F9_10_ASSET_INV_SALE_EOY, F9_10_ASSET_EXP_PREPAID_EOY, F9_10_LIAB_ACC_PAYABLE_EOY, F9_10_LIAB_GRANT_PAYABLE_EOY, F9_08_REV_CONTR_TOT, F9_08_REV_OTH_FUNDR_NET_TOT, F9_08_REV_OTH_ROY_TOT, F9_08_REV_OTH_INV_NET_TOT, F9_08_REV_MISC_TOT_TOT, F9_08_REV_OTH_INVEST_INCOME_TOT, F9_08_REV_OTH_INVEST_BOND_TOT, F9_08_REV_OTH_RENT_NET_TOT, F9_08_REV_OTH_SALE_GAIN_NET_TOT )

}


X2013.SOI.RENAME <- function(d, ein='ein'){ 

  nm <- names(d)
  nm[ nm == ein ] <- 'F9_00_ORG_EIN' 
  names(d) <- nm 
  d <- dplyr::rename( d, 
    F9_10_ASSET_CASH_SAVING_EOY = nonintcashend, 
    F9_08_REV_PROG_TOT_TOT = totprgmrevnue, 
    F9_10_LIAB_TOT_EOY = totliabend, 
    F9_10_ASSET_ACC_NET_EOY = accntsrcvblend, 
    F9_09_EXP_DEPREC_TOT = deprcatndepletn, 
    F9_10_ASSET_SAVING_EOY = svngstempinvend, 
    F9_10_ASSET_TOT_EOY = totassetsend, 
    F9_01_EXP_TOT_CY = totfuncexpns, 
    F9_10_NAFB_UNRESTRICT_EOY = unrstrctnetasstsend, 
    F9_01_REV_TOT_CY = totrevenue, 
    F9_10_ASSET_PLEDGE_NET_EOY = pldgegrntrcvblend, 
    F9_10_NAFB_TOT_EOY = totnetassetend, 
    F9_10_ASSET_INV_SALE_EOY = invntriesalesend, 
    F9_10_ASSET_EXP_PREPAID_EOY = prepaidexpnsend, 
    F9_10_LIAB_ACC_PAYABLE_EOY = accntspayableend, 
    F9_10_LIAB_GRANT_PAYABLE_EOY = grntspayableend, 
    F9_08_REV_CONTR_TOT = totcntrbgfts, 
    F9_08_REV_OTH_FUNDR_NET_TOT = netincfndrsng, 
    F9_08_REV_OTH_ROY_TOT = royaltsinc, 
    F9_08_REV_OTH_INV_NET_TOT = netincsales, 
    F9_08_REV_MISC_TOT_TOT = miscrevtot11e, 
    F9_08_REV_OTH_INVEST_INCOME_TOT = invstmntinc, 
    F9_08_REV_OTH_INVEST_BOND_TOT = txexmptbndsproceeds , 
    F9_08_REV_OTH_RENT_NET_TOT = netrntlinc , 
    F9_08_REV_OTH_SALE_GAIN_NET_TOT = netgnls ) %>%  
  dplyr::select( F9_00_ORG_EIN, F9_10_ASSET_CASH_SAVING_EOY, F9_08_REV_PROG_TOT_TOT, F9_10_LIAB_TOT_EOY, F9_10_ASSET_ACC_NET_EOY, F9_09_EXP_DEPREC_TOT, F9_10_ASSET_SAVING_EOY, F9_10_ASSET_TOT_EOY, F9_01_EXP_TOT_CY, F9_10_NAFB_UNRESTRICT_EOY, F9_01_REV_TOT_CY, F9_10_ASSET_PLEDGE_NET_EOY, F9_10_NAFB_TOT_EOY, F9_10_ASSET_INV_SALE_EOY, F9_10_ASSET_EXP_PREPAID_EOY, F9_10_LIAB_ACC_PAYABLE_EOY, F9_10_LIAB_GRANT_PAYABLE_EOY, F9_08_REV_CONTR_TOT, F9_08_REV_OTH_FUNDR_NET_TOT, F9_08_REV_OTH_ROY_TOT, F9_08_REV_OTH_INV_NET_TOT, F9_08_REV_MISC_TOT_TOT, F9_08_REV_OTH_INVEST_INCOME_TOT, F9_08_REV_OTH_INVEST_BOND_TOT, F9_08_REV_OTH_RENT_NET_TOT, F9_08_REV_OTH_SALE_GAIN_NET_TOT )

}


X2010.NCCS.RENAME <- function(d, ein='ein'){ 

  nm <- names(d)
  nm[ nm == ein ] <- 'F9_00_ORG_EIN' 
  names(d) <- nm 
  d <- dplyr::rename( d, 
    F9_10_ASSET_CASH_SAVING_EOY = CashEstimate, 
    F9_08_REV_PROG_TOT_TOT = PROGREV, 
    F9_10_LIAB_TOT_EOY = LIAB_EOY, 
    F9_09_EXP_DEPREC_TOT = DepRecEstimate, 
    F9_10_ASSET_TOT_EOY = ASS_EOY, 
    F9_01_EXP_TOT_CY = EXPS, 
    F9_10_NAFB_UNRESTRICT_EOY = UnaseoyEstimate, 
    F9_01_REV_TOT_CY = TOTREV2, 
    F9_10_NAFB_TOT_EOY = FUNDBAL, 
    F9_08_REV_CONTR_TOT = CONT, 
    F9_08_REV_OTH_FUNDR_NET_TOT = FUNDINC, 
    F9_08_REV_OTH_INV_NET_TOT = GRPROF, 
    F9_08_REV_MISC_TOT_TOT = OTHINC, 
    F9_08_REV_OTH_INVEST_INCOME_TOT = INVINC, 
    F9_08_REV_OTH_INVEST_BOND_TOT = SECINC, 
    F9_08_REV_OTH_RENT_NET_TOT = NETRENT, 
    F9_08_REV_OTH_SALE_GAIN_NET_TOT = SALESECN, 
    F9_08_REV_CONTR_GOVT_GRANT = GovGtEstimate ) %>%  
  dplyr::select( F9_00_ORG_EIN, F9_10_ASSET_CASH_SAVING_EOY, F9_08_REV_PROG_TOT_TOT, F9_10_LIAB_TOT_EOY, F9_09_EXP_DEPREC_TOT, F9_10_ASSET_TOT_EOY, F9_01_EXP_TOT_CY, F9_10_NAFB_UNRESTRICT_EOY, F9_01_REV_TOT_CY, F9_10_NAFB_TOT_EOY, F9_08_REV_CONTR_TOT, F9_08_REV_OTH_FUNDR_NET_TOT, F9_08_REV_OTH_INV_NET_TOT, F9_08_REV_MISC_TOT_TOT, F9_08_REV_OTH_INVEST_INCOME_TOT, F9_08_REV_OTH_INVEST_BOND_TOT, F9_08_REV_OTH_RENT_NET_TOT, F9_08_REV_OTH_SALE_GAIN_NET_TOT, F9_08_REV_CONTR_GOVT_GRANT )

}


X2007.NCCS.RENAME <- function(d, ein='ein'){ 

  nm <- names(d)
  nm[ nm == ein ] <- 'F9_00_ORG_EIN' 
  names(d) <- nm 
  d <- dplyr::rename( d, 
    F9_10_ASSET_CASH_SAVING_EOY = CashEstimate, 
    F9_08_REV_PROG_TOT_TOT = PROGREV, 
    F9_10_LIAB_TOT_EOY = LIAB_EOY, 
    # F9_09_EXP_DEPREC_TOT = DepRecEstimate, 
    F9_10_ASSET_TOT_EOY = ASS_EOY, 
    F9_01_EXP_TOT_CY = EXPS, 
    F9_10_NAFB_UNRESTRICT_EOY = UnaseoyEstimate, 
    F9_01_REV_TOT_CY = TOTREV2, 
    F9_10_NAFB_TOT_EOY = FUNDBAL, 
    F9_08_REV_CONTR_TOT = CONT, 
    F9_08_REV_OTH_FUNDR_NET_TOT = FUNDINC, 
    F9_08_REV_OTH_INV_NET_TOT = GRPROF, 
    F9_08_REV_MISC_TOT_TOT = OTHINC, 
    F9_08_REV_OTH_INVEST_INCOME_TOT = INVINC, 
    F9_08_REV_OTH_INVEST_BOND_TOT = SECINC, 
    F9_08_REV_OTH_RENT_NET_TOT = NETRENT, 
    F9_08_REV_OTH_SALE_GAIN_NET_TOT = SALESECN, 
    F9_08_REV_CONTR_GOVT_GRANT = GovGtEstimate ) %>%  
  dplyr::select( F9_00_ORG_EIN, F9_10_ASSET_CASH_SAVING_EOY, F9_08_REV_PROG_TOT_TOT, F9_10_LIAB_TOT_EOY, F9_10_ASSET_TOT_EOY, F9_01_EXP_TOT_CY, F9_10_NAFB_UNRESTRICT_EOY, F9_01_REV_TOT_CY, F9_10_NAFB_TOT_EOY, F9_08_REV_CONTR_TOT, F9_08_REV_OTH_FUNDR_NET_TOT, F9_08_REV_OTH_INV_NET_TOT, F9_08_REV_MISC_TOT_TOT, F9_08_REV_OTH_INVEST_INCOME_TOT, F9_08_REV_OTH_INVEST_BOND_TOT, F9_08_REV_OTH_RENT_NET_TOT, F9_08_REV_OTH_SALE_GAIN_NET_TOT, F9_08_REV_CONTR_GOVT_GRANT )

}


X2004.NCCS.RENAME <- function(d, ein='ein'){ 

  nm <- names(d)
  nm[ nm == ein ] <- 'F9_00_ORG_EIN' 
  names(d) <- nm 
  d <- dplyr::rename( d, 
    F9_10_ASSET_CASH_SAVING_EOY = CashEstimate, 
    F9_08_REV_PROG_TOT_TOT = PROGREV, 
    F9_10_LIAB_TOT_EOY = LIAB_EOY, 
    # F9_09_EXP_DEPREC_TOT = DepRecEstimate, 
    F9_10_ASSET_TOT_EOY = ASS_EOY, 
    F9_01_EXP_TOT_CY = EXPS, 
    F9_10_NAFB_UNRESTRICT_EOY = UnaseoyEstimate, 
    F9_01_REV_TOT_CY = TOTREV2, 
    F9_10_NAFB_TOT_EOY = FUNDBAL, 
    F9_08_REV_CONTR_TOT = CONT, 
    F9_08_REV_OTH_FUNDR_NET_TOT = FUNDINC, 
    F9_08_REV_OTH_INV_NET_TOT = GRPROF, 
    F9_08_REV_MISC_TOT_TOT = OTHINC, 
    F9_08_REV_OTH_INVEST_INCOME_TOT = INVINC, 
    F9_08_REV_OTH_INVEST_BOND_TOT = SECINC, 
    F9_08_REV_OTH_RENT_NET_TOT = NETRENT, 
    F9_08_REV_OTH_SALE_GAIN_NET_TOT = SALESECN, 
    F9_08_REV_CONTR_GOVT_GRANT = GovGtEstimate ) %>%  
  dplyr::select( F9_00_ORG_EIN, F9_10_ASSET_CASH_SAVING_EOY, F9_08_REV_PROG_TOT_TOT, F9_10_LIAB_TOT_EOY, F9_10_ASSET_TOT_EOY, F9_01_EXP_TOT_CY, F9_10_NAFB_UNRESTRICT_EOY, F9_01_REV_TOT_CY, F9_10_NAFB_TOT_EOY, F9_08_REV_CONTR_TOT, F9_08_REV_OTH_FUNDR_NET_TOT, F9_08_REV_OTH_INV_NET_TOT, F9_08_REV_MISC_TOT_TOT, F9_08_REV_OTH_INVEST_INCOME_TOT, F9_08_REV_OTH_INVEST_BOND_TOT, F9_08_REV_OTH_RENT_NET_TOT, F9_08_REV_OTH_SALE_GAIN_NET_TOT, F9_08_REV_CONTR_GOVT_GRANT )

}



X2001.NCCS.RENAME <- function(d, ein='ein'){ 

  nm <- names(d)
  nm[ nm == ein ] <- 'F9_00_ORG_EIN' 
  names(d) <- nm 
  d <- dplyr::rename( d, 
    F9_10_ASSET_CASH_SAVING_EOY = CashEstimate, 
    F9_08_REV_PROG_TOT_TOT = PROGREV, 
    F9_10_LIAB_TOT_EOY = LIAB_EOY, 
    F9_10_ASSET_TOT_EOY = ASS_EOY, 
    F9_01_EXP_TOT_CY = EXPS, 
    F9_10_NAFB_UNRESTRICT_EOY = UnaseoyEstimate, 
    F9_01_REV_TOT_CY = TOTREV2, 
    F9_10_NAFB_TOT_EOY = FUNDBAL, 
    F9_08_REV_CONTR_TOT = CONT, 
    F9_08_REV_OTH_FUNDR_NET_TOT = FUNDINC, 
    F9_08_REV_OTH_INV_NET_TOT = GRPROF, 
    F9_08_REV_MISC_TOT_TOT = OTHINC, 
    F9_08_REV_OTH_INVEST_INCOME_TOT = INVINC, 
    F9_08_REV_OTH_INVEST_BOND_TOT = SECINC, 
    F9_08_REV_OTH_RENT_NET_TOT = NETRENT, 
    F9_08_REV_OTH_SALE_GAIN_NET_TOT = SALESECN, 
    F9_08_REV_CONTR_GOVT_GRANT = GovGtEstimate ) %>%  
  dplyr::select( F9_00_ORG_EIN, F9_10_ASSET_CASH_SAVING_EOY, F9_08_REV_PROG_TOT_TOT, F9_10_LIAB_TOT_EOY, F9_10_ASSET_TOT_EOY, F9_01_EXP_TOT_CY, F9_10_NAFB_UNRESTRICT_EOY, F9_01_REV_TOT_CY, F9_10_NAFB_TOT_EOY, F9_08_REV_CONTR_TOT, F9_08_REV_OTH_FUNDR_NET_TOT, F9_08_REV_OTH_INV_NET_TOT, F9_08_REV_MISC_TOT_TOT, F9_08_REV_OTH_INVEST_INCOME_TOT, F9_08_REV_OTH_INVEST_BOND_TOT, F9_08_REV_OTH_RENT_NET_TOT, F9_08_REV_OTH_SALE_GAIN_NET_TOT, F9_08_REV_CONTR_GOVT_GRANT )

}





X2001.Digital.Files.RENAME <- function(d, ein='ein'){ 

  nm <- names(d)
  nm[ nm == ein ] <- 'F9_00_ORG_EIN' 
  names(d) <- nm 
  d <- dplyr::rename( d, 
    F9_10_ASSET_CASH_SAVING_EOY = CashEstimate, 
    F9_08_REV_PROG_TOT_TOT = PROGREV, 
    F9_10_LIAB_TOT_EOY = LIAB_EOY, 
    F9_10_ASSET_ACC_NET_EOY = p4g_arec, 
    F9_09_EXP_DEPREC_TOT = DepRecEstimate, 
    F9_10_ASSET_SAVING_EOY = p4e_save, 
    F9_10_ASSET_TOT_EOY = ASS_EOY, 
    F9_01_EXP_TOT_CY = EXPS, 
    F9_10_NAFB_UNRESTRICT_EOY = UnaseoyEstimate, 
    F9_01_REV_TOT_CY = TOTREV2, 
    F9_10_ASSET_PLEDGE_NET_EOY = p4e_grec + p4e_prec, 
    F9_10_NAFB_TOT_EOY = FUNDBAL, 
    F9_08_REV_CONTR_TOT = CONT, 
    F9_08_REV_OTH_FUNDR_NET_TOT = FUNDINC, 
    F9_08_REV_OTH_INV_NET_TOT = GRPROF, 
    F9_08_REV_MISC_TOT_TOT = OTHINC, 
    F9_08_REV_OTH_INVEST_INCOME_TOT = INVINC, 
    F9_08_REV_OTH_INVEST_BOND_TOT = SECINC, 
    F9_08_REV_OTH_RENT_NET_TOT = NETRENT, 
    F9_08_REV_OTH_SALE_GAIN_NET_TOT = SALESECN, 
    F9_08_REV_CONTR_GOVT_GRANT = GovGtEstimate ) %>%  
  dplyr::select( F9_00_ORG_EIN, F9_10_ASSET_CASH_SAVING_EOY, F9_08_REV_PROG_TOT_TOT, F9_10_LIAB_TOT_EOY, F9_10_ASSET_ACC_NET_EOY, F9_09_EXP_DEPREC_TOT, F9_10_ASSET_SAVING_EOY, F9_10_ASSET_TOT_EOY, F9_01_EXP_TOT_CY, F9_10_NAFB_UNRESTRICT_EOY, F9_01_REV_TOT_CY, F9_10_ASSET_PLEDGE_NET_EOY, F9_10_NAFB_TOT_EOY, F9_08_REV_CONTR_TOT, F9_08_REV_OTH_FUNDR_NET_TOT, F9_08_REV_OTH_INV_NET_TOT, F9_08_REV_MISC_TOT_TOT, F9_08_REV_OTH_INVEST_INCOME_TOT, F9_08_REV_OTH_INVEST_BOND_TOT, F9_08_REV_OTH_RENT_NET_TOT, F9_08_REV_OTH_SALE_GAIN_NET_TOT, F9_08_REV_CONTR_GOVT_GRANT )

}


